name: Publish
on: workflow_dispatch

defaults:
  run:
    shell: pwsh

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install yq
        uses: dcarbone/install-yq-action@v1.3.1

      - name: Get release version
        id: get_version
        run: |
          $v = yq .workspace.package.version tml/Cargo.toml
          "version=$v" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: >
          gh release create v${{ steps.get_version.outputs.version }}
          --repo ${{ github.event.repository.full_name }}
          --title v${{ steps.get_version.outputs.version }}
          --generate-notes

  build:
    needs:
      - release
    strategy:
      matrix:
        include:
          - rid: win-x86_64
            host_os: windows-latest
            toolchain: x86_64-pc-windows-msvc
          - rid: macos-x86_64
            host_os: macos-15-intel
            toolchain: x86_64-apple-darwin
          - rid: linux-x86_64
            host_os: ubuntu-24.04
            toolchain: x86_64-unknown-linux-gnu
          - rid: win-aarch64
            host_os: windows-11-arm
            toolchain: aarch64-pc-windows-msvc
          - rid: macos-aarch64
            host_os: macos-latest
            toolchain: aarch64-apple-darwin
          - rid: linux-aarch64
            host_os: ubuntu-24.04-arm
            toolchain: aarch64-unknown-linux-gnu
    runs-on: ${{ matrix.host_os }}
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install target toolchain
        run: |
          rustup target add ${{ matrix.toolchain }}

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "25"

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: "11"

      - name: Build
        run: |
          cd tml-ui
          pnpm install
          pnpm build
          cd ..
          mv tml-ui/dist tml/crates/tml_webapi/fontend_dist
          cd tml
          cargo build -r
          cd ..

      - name: Get metadata
        id: get_metadata
        run: |
          $version = yq .workspace.package.version tml/Cargo.toml
          "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Compress archive
        run: |
          Compress-Archive -Path "tml/target/release/tml_webapi.exe", "tml/config_example.toml" -DestinationPath "tml-${{ matrix.rid }}-v${{ steps.get_metadata.outputs.version }}.zip"

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: >
          gh release upload v${{ steps.get_metadata.outputs.version }}
          tml-${{ matrix.rid }}-v${{ steps.get_metadata.outputs.version }}.zip
          --repo ${{ github.event.repository.full_name }}
